<html>

<style  type="text/css">
table {
    border-collapse: collapse;
}

table, td, th {
    border: 1px solid black;
    border-color:#cccccc;
     border-spacing: 5px;
      height: 30px;
}
tab2{
 
}
</style>



 
 
 <div align="center" >
 
 <img src="/billnstock/WebContent/img/images/protostar_logo_pix_313_132.jpg"style="width:55px;height:55px;"/>
<b>Protostar Consulting</b>
<br></br>
Kasarwadi,pune
</div>
<hr></hr>
<p><b>Employee No.</b>324 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Department:</b></p>
<p><b>Name:</b> ${Name}</p>
<p><b>Designation: </b> </p>
<p><b> Month: </b>${Month} </P>

<br></br>
<table style="
    width: 100%;
 hight:100%; " >
   
	<tbody >
	
	 <tr>
    <th>Earnings</th>
    <th>  </th>
    <th>Deductions</th>
    <th></th>
  </tr>
  <tr>
  <td>Basic & DA</td>
  <td>0.0000000</td>
  <td>Provident Fund(PF)</td>
  <td>${PFDeductionAmt}</td>
   </tr>
	
	<tr>
  <td>Manthly Gross</td>
  <td>${ManthlyGross}</td>
  <td>Provident Fund(PF)</td>
  <td>${PTDeductionAmt}</td>
    </tr>
	
	<tr>
  <td>Pay Days</td>
  <td>${PayDays}</td>
  <td>Monthly Salary</td>
  <td>${MonthlySalary}</td>
    </tr>
    <tr>
   <td></td>
  <td></td>
  <td><b>Net Salary(PF)</b></td>
  <td>${NetSalary}</td>
    </tr>
	
	 </tbody>
		 </table>
		 
<p>*<small>This is Automatically Generated Salary</small></p>		 
		
	
  
  
  
 
</html> 