<html>

<style  type="text/css">
table {
    border-collapse: collapse;
}


tab2{
 
}
</style>



 
 
 <div align="center" >
 
 <img src="/billnstock/WebContent/img/images/protostar_logo_pix_313_132.jpg"style="width:55px;height:55px;"/>
<b>Protostar Consulting</b>
<br></br>
Kasarwadi,pune
</div>
<hr></hr>
<table  style="
    width: 100%;
 hight:100%;">
<tr>
<td  style="width:20%;">Employee No.</td>
<td>324</td>
<td></td>

<td align="right">Department: </td>
<td align="right"> </td>
</tr>
<tr>
<td  width="style="width:20%;">Employee Name: </td>
<td>${Name}</td>

</tr>
<tr>
<td  width="style="width:40%;">Designation:</td>
<td > </td><td></td>
<td  align="right">Total Days in Month:</td>
<td>${totalDays}</td>

</tr>
<tr>
<td  width="style="width:20%;">Month:</td>
<td>${Month}</td>
<td align="left"> </td>
<td  align="right">Payable Days:</td>
<td>${PayDays}</td>
</tr>
</table>

 <br></br>
  <br></br>


 <br></br>
 <p><br></br></p>
 
<table style="
    width: 100%;
 hight:100%;
  border: 1px solid black;
    border-color:#cccccc;
     border-spacing: 5px;
      height: 30px; "  >
   
	<tbody >
	
	 <tr>
    <th style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Earnings</th>
    <th style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">  </th>
    <th style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">  </th>
    <th style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Deductions</th>
    <th style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></th>
  </tr>
  
  
  <tr>
   <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Basic</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${Basic}</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Provident Fund(PF)</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${PTDeductionAmt}</td>
    </tr>
  <tr>
  
      </tr>
  
  
  <tr>
 <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">HRA</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${HRA}</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Provident Tax</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${PTDeductionAmt}</td>
   </tr>
	
	<tr>
	
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Conveyance</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${Conveyance}</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Provident Fund(PF)</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${PFDeductionAmt}</td>
	</tr>
	
	<tr>
	
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Medical</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${Medical}</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Canteen(PF)</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${Canteen}</td>
	</tr>
	<tr>
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Education</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${Education}</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">IT Dduction(PF)</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${ITDduction}</td>
	
	</tr>
	<tr>
	
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Adhoc Allow</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${AdhocAllow}</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"> Other Deduction</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${OtherDeduction}</td>
	
	</tr>
	<tr>
	
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Special Allow</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${SpecialAllow}</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
    <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  	
	</tr>
	
	<tr>
	
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">Special Allow-2</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">${SpecialAllow2}</td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
    <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  	
	</tr>
	
	<tr>
	</tr>
	<tr>
	
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"><b>Total Earnings</b></td>
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"><b>${totalEarnings}</b></td>
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
 <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"><b>Total Deduction</b></td>
	<td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"><b>${totalDeductions}</b></td>
	
	</tr>
	
    <tr>
   <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"><b>Net Salary</b></td>
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;"><b>${NetSalary}</b></td>
 
  <td style="border: 1px solid black;border-color:#cccccc; border-spacing: 5px; height: 30px;">   </td>
    </tr>
	
	 </tbody>
		 </table>
		 
<p>*<small>This is Automatically Generated Salary</small></p>		 
		
	
  
  
  
 
</html> 