<html>
 <div align="center">
 <b>${buisinessName}</b> <br></br> ${buisinessAddress}
</div>
<hr></hr>

  <div align="center">
	<b>Reciept Voucher </b>
</div>

	
	<table style="
     width: 100%;
     hight:100%;" >
   
	<tbody >
	
	
	<tr style=" height: 50px; ">
	<td><b>Credit Account: </b> ${CreditAccount}</td>
<td><b>  Debit Account:</b>  ${DebitAccount} </td></tr>
	
	<tr style=" height: 50px;">
	<td><b>Amount:</b> ${Amount}</td>
	<td ><b>Narration : </b>${Narration}</td>
	</tr>
	 </tbody>
		 </table>
		
	
  
  
  
 
</html> 