<html>
 <div align="center" >
<b>Protostar Consulting</b>
<br></br>
Kasarwadi,pune
</div>
<hr></hr>
  
<h4 align="center" style="font-size: 150%">Sales Voucher </h4>
	
	<table style="
     width: 100%;
     hight:100%;" >
   
	<tbody >
	
	
	<tr style=" height: 50px; ">
	<td><b>Debit Account : </b> ${DebitAccount}</td>
<td><b>Credit Account:</b>  ${CreditAccount} </td></tr>
	
	<tr style=" height: 50px;">
	<td><b>Amount:</b> ${Amount}</td>
	<td ><b>Narration : </b>${Narration}</td>
	</tr>
	 </tbody>
		 </table>
		
	
  
  
  
 
</html> 